name: Daily One-Pager
permissions:
  contents: write


on:
  schedule:
    - cron: "0 11 * * *"   # runs daily around 7:00 AM New York time
  workflow_dispatch:       # lets you run it manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Generate today’s page
        run: python scripts/generate.py

      - name: Commit & push
        run: |
          git config user.name "daily-bot"
          git config user.email "bot@example.com"
          git add -A
          git commit -m "daily: update one-pager" || echo "no changes"
          git push
